version: "3.1"

services:

  nginx:
    image: nginx:1.12-alpine
    ports:
      - "8000:80"
    volumes:
      - ./php/content:/srv/www/content
      - ./static:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php:php-app
      - nodejs:nodejs-app

  nodejs:
    image: node:8.9-alpine
    environment: 
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    volumes:
      - ./nodejs:/home/app
    links:
      - php:php-app
    command: ["node", "index"]

  php:
    image: php:7.2-apache
    volumes:
      - ./php:/var/www/html